CREATE OR REPLACE DATABASE WHOOP;

CREATE STAGE WHOOP.PUBLIC.PDFS 
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE STAGE WHOOP.PUBLIC.SEMANTIC_MODELS 
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE STAGE WHOOP.PUBLIC.RAW_DATA 
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );