CREATE OR REPLACE CORTEX SEARCH SERVICE  WHOOP.DOCUMENTS.LOCKER_SEARCH
  ON CONTENT
  ATTRIBUTES PUBLICATION_DATE
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 day'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
  AS (
    SELECT
        CONTENT,
        PUBLICATION_DATE,
        PUBLICATION_TITLE,
        PUBLICATION_ID
    FROM WHOOP.DOCUMENTS.LOCKER_DATA
);

CREATE OR REPLACE CORTEX SEARCH SERVICE  WHOOP.DOCUMENTS.PDF_SEARCH
  ON CHUNK
  ATTRIBUTES LANGUAGE
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 day'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
  AS (
    SELECT
        CHUNK,
        FILE_URL,
        LANGUAGE,
        RELATIVE_PATH
    FROM WHOOP.DOCUMENTS.DOCS_CHUNKS_TABLE
);
